### ISSUE TITLE
Reformer example on colab: Other book fail.

### ISSUE THREAD

**Issue by j2l** [google/trax#270]
### Description
I generated (size=320) bpe vocab and model files and compared with Crimes & Punishment files and everything went OK 
`Number of tokens: 750515` and `(device count, tokens per device) =  (8, 1048576)`
until training:
`RuntimeError: Resource exhausted: Ran out of memory in memory space hbm. Used 18.74G of 8.00G hbm. Exceeded hbm capacity by 10.74G.`
Wow, a 50% tokens increase jumps 512M to 18G?
Or did I miss something else?

### Environment information
https://colab.research.google.com/github/google/trax/blob/master/trax/models/reformer/text_generation.ipynb

**Comment by nkitaev** [comment]
It looks like you doubled the number of tokens per device, and memory usage increased just slightly over 2x. The 8.00G hbm limit that's being reported in the error message is the amount of memory available *per device*. With 0.5 million tokens per device (as in the example), memory usage fits in the 8.00G of hbm. You doubled that, so you'd expect to see something like 16.00G of HBM usage -- instead you see 18.74G. This isn't too surprising because the way hyperparameters are currently specified, multiple hyperparameters need to be changed when you change the sequence length, and you might have missed one.
